// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0
// 	protoc        v3.5.1
// source: rtm.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type RTMMsgType_RTMMsgEnum int32

const (
	RTMMsgType_Private RTMMsgType_RTMMsgEnum = 0
	RTMMsgType_Room    RTMMsgType_RTMMsgEnum = 1
)

// Enum value maps for RTMMsgType_RTMMsgEnum.
var (
	RTMMsgType_RTMMsgEnum_name = map[int32]string{
		0: "Private",
		1: "Room",
	}
	RTMMsgType_RTMMsgEnum_value = map[string]int32{
		"Private": 0,
		"Room":    1,
	}
)

func (x RTMMsgType_RTMMsgEnum) Enum() *RTMMsgType_RTMMsgEnum {
	p := new(RTMMsgType_RTMMsgEnum)
	*p = x
	return p
}

func (x RTMMsgType_RTMMsgEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RTMMsgType_RTMMsgEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_rtm_proto_enumTypes[0].Descriptor()
}

func (RTMMsgType_RTMMsgEnum) Type() protoreflect.EnumType {
	return &file_rtm_proto_enumTypes[0]
}

func (x RTMMsgType_RTMMsgEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RTMMsgType_RTMMsgEnum.Descriptor instead.
func (RTMMsgType_RTMMsgEnum) EnumDescriptor() ([]byte, []int) {
	return file_rtm_proto_rawDescGZIP(), []int{0, 0}
}

type RTMMsgErrType_RTMMsgErrEnum int32

const (
	RTMMsgErrType_RecvUserNoOnline RTMMsgErrType_RTMMsgErrEnum = 0
	RTMMsgErrType_UserSessionErr   RTMMsgErrType_RTMMsgErrEnum = 1
)

// Enum value maps for RTMMsgErrType_RTMMsgErrEnum.
var (
	RTMMsgErrType_RTMMsgErrEnum_name = map[int32]string{
		0: "RecvUserNoOnline",
		1: "UserSessionErr",
	}
	RTMMsgErrType_RTMMsgErrEnum_value = map[string]int32{
		"RecvUserNoOnline": 0,
		"UserSessionErr":   1,
	}
)

func (x RTMMsgErrType_RTMMsgErrEnum) Enum() *RTMMsgErrType_RTMMsgErrEnum {
	p := new(RTMMsgErrType_RTMMsgErrEnum)
	*p = x
	return p
}

func (x RTMMsgErrType_RTMMsgErrEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RTMMsgErrType_RTMMsgErrEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_rtm_proto_enumTypes[1].Descriptor()
}

func (RTMMsgErrType_RTMMsgErrEnum) Type() protoreflect.EnumType {
	return &file_rtm_proto_enumTypes[1]
}

func (x RTMMsgErrType_RTMMsgErrEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RTMMsgErrType_RTMMsgErrEnum.Descriptor instead.
func (RTMMsgErrType_RTMMsgErrEnum) EnumDescriptor() ([]byte, []int) {
	return file_rtm_proto_rawDescGZIP(), []int{1, 0}
}

type C2S_MsgID_MsgID int32

const (
	C2S_MsgID_LoginRTM     C2S_MsgID_MsgID = 0
	C2S_MsgID_SendRTM      C2S_MsgID_MsgID = 1
	C2S_MsgID_JoinRoomChan C2S_MsgID_MsgID = 2
	C2S_MsgID_QuitRoomChan C2S_MsgID_MsgID = 3
)

// Enum value maps for C2S_MsgID_MsgID.
var (
	C2S_MsgID_MsgID_name = map[int32]string{
		0: "LoginRTM",
		1: "SendRTM",
		2: "JoinRoomChan",
		3: "QuitRoomChan",
	}
	C2S_MsgID_MsgID_value = map[string]int32{
		"LoginRTM":     0,
		"SendRTM":      1,
		"JoinRoomChan": 2,
		"QuitRoomChan": 3,
	}
)

func (x C2S_MsgID_MsgID) Enum() *C2S_MsgID_MsgID {
	p := new(C2S_MsgID_MsgID)
	*p = x
	return p
}

func (x C2S_MsgID_MsgID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (C2S_MsgID_MsgID) Descriptor() protoreflect.EnumDescriptor {
	return file_rtm_proto_enumTypes[2].Descriptor()
}

func (C2S_MsgID_MsgID) Type() protoreflect.EnumType {
	return &file_rtm_proto_enumTypes[2]
}

func (x C2S_MsgID_MsgID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use C2S_MsgID_MsgID.Descriptor instead.
func (C2S_MsgID_MsgID) EnumDescriptor() ([]byte, []int) {
	return file_rtm_proto_rawDescGZIP(), []int{2, 0}
}

type S2C_MsgID_MsgID int32

const (
	S2C_MsgID_LoginOK            S2C_MsgID_MsgID = 0
	S2C_MsgID_LoginFail          S2C_MsgID_MsgID = 1
	S2C_MsgID_RTMMsgErr          S2C_MsgID_MsgID = 2
	S2C_MsgID_EventNotify        S2C_MsgID_MsgID = 3
	S2C_MsgID_RecvRTM            S2C_MsgID_MsgID = 11
	S2C_MsgID_JoinRoomChanOK     S2C_MsgID_MsgID = 12
	S2C_MsgID_JoinRoomChanFailed S2C_MsgID_MsgID = 13
)

// Enum value maps for S2C_MsgID_MsgID.
var (
	S2C_MsgID_MsgID_name = map[int32]string{
		0:  "LoginOK",
		1:  "LoginFail",
		2:  "RTMMsgErr",
		3:  "EventNotify",
		11: "RecvRTM",
		12: "JoinRoomChanOK",
		13: "JoinRoomChanFailed",
	}
	S2C_MsgID_MsgID_value = map[string]int32{
		"LoginOK":            0,
		"LoginFail":          1,
		"RTMMsgErr":          2,
		"EventNotify":        3,
		"RecvRTM":            11,
		"JoinRoomChanOK":     12,
		"JoinRoomChanFailed": 13,
	}
)

func (x S2C_MsgID_MsgID) Enum() *S2C_MsgID_MsgID {
	p := new(S2C_MsgID_MsgID)
	*p = x
	return p
}

func (x S2C_MsgID_MsgID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (S2C_MsgID_MsgID) Descriptor() protoreflect.EnumDescriptor {
	return file_rtm_proto_enumTypes[3].Descriptor()
}

func (S2C_MsgID_MsgID) Type() protoreflect.EnumType {
	return &file_rtm_proto_enumTypes[3]
}

func (x S2C_MsgID_MsgID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use S2C_MsgID_MsgID.Descriptor instead.
func (S2C_MsgID_MsgID) EnumDescriptor() ([]byte, []int) {
	return file_rtm_proto_rawDescGZIP(), []int{7, 0}
}

type RTMMsgType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RTMMsgType) Reset() {
	*x = RTMMsgType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rtm_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RTMMsgType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RTMMsgType) ProtoMessage() {}

func (x *RTMMsgType) ProtoReflect() protoreflect.Message {
	mi := &file_rtm_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RTMMsgType.ProtoReflect.Descriptor instead.
func (*RTMMsgType) Descriptor() ([]byte, []int) {
	return file_rtm_proto_rawDescGZIP(), []int{0}
}

type RTMMsgErrType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RTMMsgErrType) Reset() {
	*x = RTMMsgErrType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rtm_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RTMMsgErrType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RTMMsgErrType) ProtoMessage() {}

func (x *RTMMsgErrType) ProtoReflect() protoreflect.Message {
	mi := &file_rtm_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RTMMsgErrType.ProtoReflect.Descriptor instead.
func (*RTMMsgErrType) Descriptor() ([]byte, []int) {
	return file_rtm_proto_rawDescGZIP(), []int{1}
}

//*
//客户端发送给服务器消息id
type C2S_MsgID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *C2S_MsgID) Reset() {
	*x = C2S_MsgID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rtm_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2S_MsgID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_MsgID) ProtoMessage() {}

func (x *C2S_MsgID) ProtoReflect() protoreflect.Message {
	mi := &file_rtm_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_MsgID.ProtoReflect.Descriptor instead.
func (*C2S_MsgID) Descriptor() ([]byte, []int) {
	return file_rtm_proto_rawDescGZIP(), []int{2}
}

// LoginRTM   =0;
type C2S_RTMMsgLogin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserSession string `protobuf:"bytes,1,opt,name=userSession,proto3" json:"userSession,omitempty"`
}

func (x *C2S_RTMMsgLogin) Reset() {
	*x = C2S_RTMMsgLogin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rtm_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2S_RTMMsgLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_RTMMsgLogin) ProtoMessage() {}

func (x *C2S_RTMMsgLogin) ProtoReflect() protoreflect.Message {
	mi := &file_rtm_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_RTMMsgLogin.ProtoReflect.Descriptor instead.
func (*C2S_RTMMsgLogin) Descriptor() ([]byte, []int) {
	return file_rtm_proto_rawDescGZIP(), []int{3}
}

func (x *C2S_RTMMsgLogin) GetUserSession() string {
	if x != nil {
		return x.UserSession
	}
	return ""
}

// SendRTM    =1;
type C2S_RTMMsgSend struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RtmType    RTMMsgType_RTMMsgEnum `protobuf:"varint,1,opt,name=rtmType,proto3,enum=pb.RTMMsgType_RTMMsgEnum" json:"rtmType,omitempty"`
	SendName   string                `protobuf:"bytes,2,opt,name=sendName,proto3" json:"sendName,omitempty"`
	SendUserID string                `protobuf:"bytes,3,opt,name=sendUserID,proto3" json:"sendUserID,omitempty"`
	ConvID     string                `protobuf:"bytes,4,opt,name=convID,proto3" json:"convID,omitempty"` // rtmtype private为userId  room 为相应id
	Msg        string                `protobuf:"bytes,5,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *C2S_RTMMsgSend) Reset() {
	*x = C2S_RTMMsgSend{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rtm_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2S_RTMMsgSend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_RTMMsgSend) ProtoMessage() {}

func (x *C2S_RTMMsgSend) ProtoReflect() protoreflect.Message {
	mi := &file_rtm_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_RTMMsgSend.ProtoReflect.Descriptor instead.
func (*C2S_RTMMsgSend) Descriptor() ([]byte, []int) {
	return file_rtm_proto_rawDescGZIP(), []int{4}
}

func (x *C2S_RTMMsgSend) GetRtmType() RTMMsgType_RTMMsgEnum {
	if x != nil {
		return x.RtmType
	}
	return RTMMsgType_Private
}

func (x *C2S_RTMMsgSend) GetSendName() string {
	if x != nil {
		return x.SendName
	}
	return ""
}

func (x *C2S_RTMMsgSend) GetSendUserID() string {
	if x != nil {
		return x.SendUserID
	}
	return ""
}

func (x *C2S_RTMMsgSend) GetConvID() string {
	if x != nil {
		return x.ConvID
	}
	return ""
}

func (x *C2S_RTMMsgSend) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// JoinRoomChan    =2;
type C2S_JoinRoomChan struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomID string `protobuf:"bytes,1,opt,name=roomID,proto3" json:"roomID,omitempty"`
}

func (x *C2S_JoinRoomChan) Reset() {
	*x = C2S_JoinRoomChan{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rtm_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2S_JoinRoomChan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_JoinRoomChan) ProtoMessage() {}

func (x *C2S_JoinRoomChan) ProtoReflect() protoreflect.Message {
	mi := &file_rtm_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_JoinRoomChan.ProtoReflect.Descriptor instead.
func (*C2S_JoinRoomChan) Descriptor() ([]byte, []int) {
	return file_rtm_proto_rawDescGZIP(), []int{5}
}

func (x *C2S_JoinRoomChan) GetRoomID() string {
	if x != nil {
		return x.RoomID
	}
	return ""
}

// QuitRoomChan    =3;
type C2S_QuitRoomChan struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomID string `protobuf:"bytes,1,opt,name=roomID,proto3" json:"roomID,omitempty"`
}

func (x *C2S_QuitRoomChan) Reset() {
	*x = C2S_QuitRoomChan{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rtm_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C2S_QuitRoomChan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2S_QuitRoomChan) ProtoMessage() {}

func (x *C2S_QuitRoomChan) ProtoReflect() protoreflect.Message {
	mi := &file_rtm_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2S_QuitRoomChan.ProtoReflect.Descriptor instead.
func (*C2S_QuitRoomChan) Descriptor() ([]byte, []int) {
	return file_rtm_proto_rawDescGZIP(), []int{6}
}

func (x *C2S_QuitRoomChan) GetRoomID() string {
	if x != nil {
		return x.RoomID
	}
	return ""
}

//*
//服务器发送给客户端消息id
type S2C_MsgID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *S2C_MsgID) Reset() {
	*x = S2C_MsgID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rtm_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_MsgID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_MsgID) ProtoMessage() {}

func (x *S2C_MsgID) ProtoReflect() protoreflect.Message {
	mi := &file_rtm_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_MsgID.ProtoReflect.Descriptor instead.
func (*S2C_MsgID) Descriptor() ([]byte, []int) {
	return file_rtm_proto_rawDescGZIP(), []int{7}
}

// LoginOK     =0;
type S2C_LoginOK struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID string `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
}

func (x *S2C_LoginOK) Reset() {
	*x = S2C_LoginOK{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rtm_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_LoginOK) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_LoginOK) ProtoMessage() {}

func (x *S2C_LoginOK) ProtoReflect() protoreflect.Message {
	mi := &file_rtm_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_LoginOK.ProtoReflect.Descriptor instead.
func (*S2C_LoginOK) Descriptor() ([]byte, []int) {
	return file_rtm_proto_rawDescGZIP(), []int{8}
}

func (x *S2C_LoginOK) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

// LoginFail   =1;
type S2C_LoginFail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err RTMMsgErrType_RTMMsgErrEnum `protobuf:"varint,1,opt,name=err,proto3,enum=pb.RTMMsgErrType_RTMMsgErrEnum" json:"err,omitempty"`
}

func (x *S2C_LoginFail) Reset() {
	*x = S2C_LoginFail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rtm_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_LoginFail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_LoginFail) ProtoMessage() {}

func (x *S2C_LoginFail) ProtoReflect() protoreflect.Message {
	mi := &file_rtm_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_LoginFail.ProtoReflect.Descriptor instead.
func (*S2C_LoginFail) Descriptor() ([]byte, []int) {
	return file_rtm_proto_rawDescGZIP(), []int{9}
}

func (x *S2C_LoginFail) GetErr() RTMMsgErrType_RTMMsgErrEnum {
	if x != nil {
		return x.Err
	}
	return RTMMsgErrType_RecvUserNoOnline
}

// RecvRTM    =11;
type S2C_RTMMsgRecv struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RtmType    RTMMsgType_RTMMsgEnum `protobuf:"varint,1,opt,name=rtmType,proto3,enum=pb.RTMMsgType_RTMMsgEnum" json:"rtmType,omitempty"`
	SendName   string                `protobuf:"bytes,2,opt,name=sendName,proto3" json:"sendName,omitempty"`
	SendUserID string                `protobuf:"bytes,3,opt,name=sendUserID,proto3" json:"sendUserID,omitempty"`
	ConvID     string                `protobuf:"bytes,4,opt,name=convID,proto3" json:"convID,omitempty"`
	Msg        string                `protobuf:"bytes,5,opt,name=msg,proto3" json:"msg,omitempty"`
	SendTime   int64                 `protobuf:"varint,6,opt,name=sendTime,proto3" json:"sendTime,omitempty"`
}

func (x *S2C_RTMMsgRecv) Reset() {
	*x = S2C_RTMMsgRecv{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rtm_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_RTMMsgRecv) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_RTMMsgRecv) ProtoMessage() {}

func (x *S2C_RTMMsgRecv) ProtoReflect() protoreflect.Message {
	mi := &file_rtm_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_RTMMsgRecv.ProtoReflect.Descriptor instead.
func (*S2C_RTMMsgRecv) Descriptor() ([]byte, []int) {
	return file_rtm_proto_rawDescGZIP(), []int{10}
}

func (x *S2C_RTMMsgRecv) GetRtmType() RTMMsgType_RTMMsgEnum {
	if x != nil {
		return x.RtmType
	}
	return RTMMsgType_Private
}

func (x *S2C_RTMMsgRecv) GetSendName() string {
	if x != nil {
		return x.SendName
	}
	return ""
}

func (x *S2C_RTMMsgRecv) GetSendUserID() string {
	if x != nil {
		return x.SendUserID
	}
	return ""
}

func (x *S2C_RTMMsgRecv) GetConvID() string {
	if x != nil {
		return x.ConvID
	}
	return ""
}

func (x *S2C_RTMMsgRecv) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *S2C_RTMMsgRecv) GetSendTime() int64 {
	if x != nil {
		return x.SendTime
	}
	return 0
}

// JoinRoomChanOK     =12;
type S2C_JoinRoomChanOK struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomID string `protobuf:"bytes,1,opt,name=roomID,proto3" json:"roomID,omitempty"`
}

func (x *S2C_JoinRoomChanOK) Reset() {
	*x = S2C_JoinRoomChanOK{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rtm_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_JoinRoomChanOK) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_JoinRoomChanOK) ProtoMessage() {}

func (x *S2C_JoinRoomChanOK) ProtoReflect() protoreflect.Message {
	mi := &file_rtm_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_JoinRoomChanOK.ProtoReflect.Descriptor instead.
func (*S2C_JoinRoomChanOK) Descriptor() ([]byte, []int) {
	return file_rtm_proto_rawDescGZIP(), []int{11}
}

func (x *S2C_JoinRoomChanOK) GetRoomID() string {
	if x != nil {
		return x.RoomID
	}
	return ""
}

// JoinRoomChanFailed  =13;
type S2C_JoinRoomChanFailed struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *S2C_JoinRoomChanFailed) Reset() {
	*x = S2C_JoinRoomChanFailed{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rtm_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_JoinRoomChanFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_JoinRoomChanFailed) ProtoMessage() {}

func (x *S2C_JoinRoomChanFailed) ProtoReflect() protoreflect.Message {
	mi := &file_rtm_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_JoinRoomChanFailed.ProtoReflect.Descriptor instead.
func (*S2C_JoinRoomChanFailed) Descriptor() ([]byte, []int) {
	return file_rtm_proto_rawDescGZIP(), []int{12}
}

//RTMErr     =2;
type S2C_RTMMsgErr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RtmType RTMMsgType_RTMMsgEnum       `protobuf:"varint,1,opt,name=rtmType,proto3,enum=pb.RTMMsgType_RTMMsgEnum" json:"rtmType,omitempty"`
	RtmErr  RTMMsgErrType_RTMMsgErrEnum `protobuf:"varint,2,opt,name=rtmErr,proto3,enum=pb.RTMMsgErrType_RTMMsgErrEnum" json:"rtmErr,omitempty"`
}

func (x *S2C_RTMMsgErr) Reset() {
	*x = S2C_RTMMsgErr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rtm_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_RTMMsgErr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_RTMMsgErr) ProtoMessage() {}

func (x *S2C_RTMMsgErr) ProtoReflect() protoreflect.Message {
	mi := &file_rtm_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_RTMMsgErr.ProtoReflect.Descriptor instead.
func (*S2C_RTMMsgErr) Descriptor() ([]byte, []int) {
	return file_rtm_proto_rawDescGZIP(), []int{13}
}

func (x *S2C_RTMMsgErr) GetRtmType() RTMMsgType_RTMMsgEnum {
	if x != nil {
		return x.RtmType
	}
	return RTMMsgType_Private
}

func (x *S2C_RTMMsgErr) GetRtmErr() RTMMsgErrType_RTMMsgErrEnum {
	if x != nil {
		return x.RtmErr
	}
	return RTMMsgErrType_RecvUserNoOnline
}

//// eventType
type S2C_EventNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventType int32  `protobuf:"varint,1,opt,name=eventType,proto3" json:"eventType,omitempty"`
	Msg       string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *S2C_EventNotify) Reset() {
	*x = S2C_EventNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rtm_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *S2C_EventNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2C_EventNotify) ProtoMessage() {}

func (x *S2C_EventNotify) ProtoReflect() protoreflect.Message {
	mi := &file_rtm_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2C_EventNotify.ProtoReflect.Descriptor instead.
func (*S2C_EventNotify) Descriptor() ([]byte, []int) {
	return file_rtm_proto_rawDescGZIP(), []int{14}
}

func (x *S2C_EventNotify) GetEventType() int32 {
	if x != nil {
		return x.EventType
	}
	return 0
}

func (x *S2C_EventNotify) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_rtm_proto protoreflect.FileDescriptor

var file_rtm_proto_rawDesc = []byte{
	0x0a, 0x09, 0x72, 0x74, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22,
	0x31, 0x0a, 0x0a, 0x52, 0x54, 0x4d, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x22, 0x23, 0x0a,
	0x0a, 0x52, 0x54, 0x4d, 0x4d, 0x73, 0x67, 0x45, 0x6e, 0x75, 0x6d, 0x12, 0x0b, 0x0a, 0x07, 0x50,
	0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x52, 0x6f, 0x6f, 0x6d,
	0x10, 0x01, 0x22, 0x4a, 0x0a, 0x0d, 0x52, 0x54, 0x4d, 0x4d, 0x73, 0x67, 0x45, 0x72, 0x72, 0x54,
	0x79, 0x70, 0x65, 0x22, 0x39, 0x0a, 0x0d, 0x52, 0x54, 0x4d, 0x4d, 0x73, 0x67, 0x45, 0x72, 0x72,
	0x45, 0x6e, 0x75, 0x6d, 0x12, 0x14, 0x0a, 0x10, 0x52, 0x65, 0x63, 0x76, 0x55, 0x73, 0x65, 0x72,
	0x4e, 0x6f, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x55, 0x73,
	0x65, 0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x45, 0x72, 0x72, 0x10, 0x01, 0x22, 0x53,
	0x0a, 0x09, 0x43, 0x32, 0x53, 0x5f, 0x4d, 0x73, 0x67, 0x49, 0x44, 0x22, 0x46, 0x0a, 0x05, 0x4d,
	0x73, 0x67, 0x49, 0x44, 0x12, 0x0c, 0x0a, 0x08, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x54, 0x4d,
	0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x54, 0x4d, 0x10, 0x01, 0x12,
	0x10, 0x0a, 0x0c, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x6f, 0x6f, 0x6d, 0x43, 0x68, 0x61, 0x6e, 0x10,
	0x02, 0x12, 0x10, 0x0a, 0x0c, 0x51, 0x75, 0x69, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x43, 0x68, 0x61,
	0x6e, 0x10, 0x03, 0x22, 0x33, 0x0a, 0x0f, 0x43, 0x32, 0x53, 0x5f, 0x52, 0x54, 0x4d, 0x4d, 0x73,
	0x67, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x53, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x75, 0x73, 0x65,
	0x72, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0xab, 0x01, 0x0a, 0x0e, 0x43, 0x32, 0x53,
	0x5f, 0x52, 0x54, 0x4d, 0x4d, 0x73, 0x67, 0x53, 0x65, 0x6e, 0x64, 0x12, 0x33, 0x0a, 0x07, 0x72,
	0x74, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x70,
	0x62, 0x2e, 0x52, 0x54, 0x4d, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x52, 0x54, 0x4d,
	0x4d, 0x73, 0x67, 0x45, 0x6e, 0x75, 0x6d, 0x52, 0x07, 0x72, 0x74, 0x6d, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a,
	0x73, 0x65, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x73, 0x65, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06,
	0x63, 0x6f, 0x6e, 0x76, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6f,
	0x6e, 0x76, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x2a, 0x0a, 0x10, 0x43, 0x32, 0x53, 0x5f, 0x4a, 0x6f,
	0x69, 0x6e, 0x52, 0x6f, 0x6f, 0x6d, 0x43, 0x68, 0x61, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f,
	0x6f, 0x6d, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d,
	0x49, 0x44, 0x22, 0x2a, 0x0a, 0x10, 0x43, 0x32, 0x53, 0x5f, 0x51, 0x75, 0x69, 0x74, 0x52, 0x6f,
	0x6f, 0x6d, 0x43, 0x68, 0x61, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x22, 0x89,
	0x01, 0x0a, 0x09, 0x53, 0x32, 0x43, 0x5f, 0x4d, 0x73, 0x67, 0x49, 0x44, 0x22, 0x7c, 0x0a, 0x05,
	0x4d, 0x73, 0x67, 0x49, 0x44, 0x12, 0x0b, 0x0a, 0x07, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x4f, 0x4b,
	0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x46, 0x61, 0x69, 0x6c, 0x10,
	0x01, 0x12, 0x0d, 0x0a, 0x09, 0x52, 0x54, 0x4d, 0x4d, 0x73, 0x67, 0x45, 0x72, 0x72, 0x10, 0x02,
	0x12, 0x0f, 0x0a, 0x0b, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x10,
	0x03, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x65, 0x63, 0x76, 0x52, 0x54, 0x4d, 0x10, 0x0b, 0x12, 0x12,
	0x0a, 0x0e, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x6f, 0x6f, 0x6d, 0x43, 0x68, 0x61, 0x6e, 0x4f, 0x4b,
	0x10, 0x0c, 0x12, 0x16, 0x0a, 0x12, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x6f, 0x6f, 0x6d, 0x43, 0x68,
	0x61, 0x6e, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x10, 0x0d, 0x22, 0x25, 0x0a, 0x0b, 0x53, 0x32,
	0x43, 0x5f, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x4f, 0x4b, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x44, 0x22, 0x42, 0x0a, 0x0d, 0x53, 0x32, 0x43, 0x5f, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x46, 0x61,
	0x69, 0x6c, 0x12, 0x31, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x1f, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x54, 0x4d, 0x4d, 0x73, 0x67, 0x45, 0x72, 0x72, 0x54, 0x79,
	0x70, 0x65, 0x2e, 0x52, 0x54, 0x4d, 0x4d, 0x73, 0x67, 0x45, 0x72, 0x72, 0x45, 0x6e, 0x75, 0x6d,
	0x52, 0x03, 0x65, 0x72, 0x72, 0x22, 0xc7, 0x01, 0x0a, 0x0e, 0x53, 0x32, 0x43, 0x5f, 0x52, 0x54,
	0x4d, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x63, 0x76, 0x12, 0x33, 0x0a, 0x07, 0x72, 0x74, 0x6d, 0x54,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x52,
	0x54, 0x4d, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x52, 0x54, 0x4d, 0x4d, 0x73, 0x67,
	0x45, 0x6e, 0x75, 0x6d, 0x52, 0x07, 0x72, 0x74, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x73, 0x65, 0x6e, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x73, 0x65, 0x6e, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x65, 0x6e,
	0x64, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73,
	0x65, 0x6e, 0x64, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6e,
	0x76, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x76, 0x49,
	0x44, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6d, 0x73, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x22,
	0x2c, 0x0a, 0x12, 0x53, 0x32, 0x43, 0x5f, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x6f, 0x6f, 0x6d, 0x43,
	0x68, 0x61, 0x6e, 0x4f, 0x4b, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x22, 0x18, 0x0a,
	0x16, 0x53, 0x32, 0x43, 0x5f, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x6f, 0x6f, 0x6d, 0x43, 0x68, 0x61,
	0x6e, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x22, 0x7d, 0x0a, 0x0d, 0x53, 0x32, 0x43, 0x5f, 0x52,
	0x54, 0x4d, 0x4d, 0x73, 0x67, 0x45, 0x72, 0x72, 0x12, 0x33, 0x0a, 0x07, 0x72, 0x74, 0x6d, 0x54,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x52,
	0x54, 0x4d, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x52, 0x54, 0x4d, 0x4d, 0x73, 0x67,
	0x45, 0x6e, 0x75, 0x6d, 0x52, 0x07, 0x72, 0x74, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x12, 0x37, 0x0a,
	0x06, 0x72, 0x74, 0x6d, 0x45, 0x72, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1f, 0x2e,
	0x70, 0x62, 0x2e, 0x52, 0x54, 0x4d, 0x4d, 0x73, 0x67, 0x45, 0x72, 0x72, 0x54, 0x79, 0x70, 0x65,
	0x2e, 0x52, 0x54, 0x4d, 0x4d, 0x73, 0x67, 0x45, 0x72, 0x72, 0x45, 0x6e, 0x75, 0x6d, 0x52, 0x06,
	0x72, 0x74, 0x6d, 0x45, 0x72, 0x72, 0x22, 0x41, 0x0a, 0x0f, 0x53, 0x32, 0x43, 0x5f, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x3b, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rtm_proto_rawDescOnce sync.Once
	file_rtm_proto_rawDescData = file_rtm_proto_rawDesc
)

func file_rtm_proto_rawDescGZIP() []byte {
	file_rtm_proto_rawDescOnce.Do(func() {
		file_rtm_proto_rawDescData = protoimpl.X.CompressGZIP(file_rtm_proto_rawDescData)
	})
	return file_rtm_proto_rawDescData
}

var file_rtm_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_rtm_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_rtm_proto_goTypes = []interface{}{
	(RTMMsgType_RTMMsgEnum)(0),       // 0: pb.RTMMsgType.RTMMsgEnum
	(RTMMsgErrType_RTMMsgErrEnum)(0), // 1: pb.RTMMsgErrType.RTMMsgErrEnum
	(C2S_MsgID_MsgID)(0),             // 2: pb.C2S_MsgID.MsgID
	(S2C_MsgID_MsgID)(0),             // 3: pb.S2C_MsgID.MsgID
	(*RTMMsgType)(nil),               // 4: pb.RTMMsgType
	(*RTMMsgErrType)(nil),            // 5: pb.RTMMsgErrType
	(*C2S_MsgID)(nil),                // 6: pb.C2S_MsgID
	(*C2S_RTMMsgLogin)(nil),          // 7: pb.C2S_RTMMsgLogin
	(*C2S_RTMMsgSend)(nil),           // 8: pb.C2S_RTMMsgSend
	(*C2S_JoinRoomChan)(nil),         // 9: pb.C2S_JoinRoomChan
	(*C2S_QuitRoomChan)(nil),         // 10: pb.C2S_QuitRoomChan
	(*S2C_MsgID)(nil),                // 11: pb.S2C_MsgID
	(*S2C_LoginOK)(nil),              // 12: pb.S2C_LoginOK
	(*S2C_LoginFail)(nil),            // 13: pb.S2C_LoginFail
	(*S2C_RTMMsgRecv)(nil),           // 14: pb.S2C_RTMMsgRecv
	(*S2C_JoinRoomChanOK)(nil),       // 15: pb.S2C_JoinRoomChanOK
	(*S2C_JoinRoomChanFailed)(nil),   // 16: pb.S2C_JoinRoomChanFailed
	(*S2C_RTMMsgErr)(nil),            // 17: pb.S2C_RTMMsgErr
	(*S2C_EventNotify)(nil),          // 18: pb.S2C_EventNotify
}
var file_rtm_proto_depIdxs = []int32{
	0, // 0: pb.C2S_RTMMsgSend.rtmType:type_name -> pb.RTMMsgType.RTMMsgEnum
	1, // 1: pb.S2C_LoginFail.err:type_name -> pb.RTMMsgErrType.RTMMsgErrEnum
	0, // 2: pb.S2C_RTMMsgRecv.rtmType:type_name -> pb.RTMMsgType.RTMMsgEnum
	0, // 3: pb.S2C_RTMMsgErr.rtmType:type_name -> pb.RTMMsgType.RTMMsgEnum
	1, // 4: pb.S2C_RTMMsgErr.rtmErr:type_name -> pb.RTMMsgErrType.RTMMsgErrEnum
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_rtm_proto_init() }
func file_rtm_proto_init() {
	if File_rtm_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rtm_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RTMMsgType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rtm_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RTMMsgErrType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rtm_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2S_MsgID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rtm_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2S_RTMMsgLogin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rtm_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2S_RTMMsgSend); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rtm_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2S_JoinRoomChan); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rtm_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C2S_QuitRoomChan); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rtm_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2C_MsgID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rtm_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2C_LoginOK); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rtm_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2C_LoginFail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rtm_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2C_RTMMsgRecv); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rtm_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2C_JoinRoomChanOK); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rtm_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2C_JoinRoomChanFailed); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rtm_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2C_RTMMsgErr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rtm_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*S2C_EventNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rtm_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rtm_proto_goTypes,
		DependencyIndexes: file_rtm_proto_depIdxs,
		EnumInfos:         file_rtm_proto_enumTypes,
		MessageInfos:      file_rtm_proto_msgTypes,
	}.Build()
	File_rtm_proto = out.File
	file_rtm_proto_rawDesc = nil
	file_rtm_proto_goTypes = nil
	file_rtm_proto_depIdxs = nil
}
